name: CD pipeline

on: 
  workflow_run:
    workflows: ["CI pipeline"]
    types:
      - completed

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: pull docker image
      run: sudo docker pull glynd21/vue-todo-app:latest
    
    - name: delete legacy containers
      run: |
        sudo docker stop vue-todo-app || true
        sudo docker rm -f vue-todo-app || true
    - name: start docker container
      run: sudo docker run -d -p 8080:8080 --name vue-todo-app glynd21/vue-todo-app